version: '3.8'

services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - flask-api
    environment:
      - DSN=postgres://user:password@postgres:5432/dbname
      - JWT_SECRET=your_jwt_secret
      - REFRESH_SECRET=your_refresh_secret
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
      - MINIO_USE_SSL=false

  flask-api:
    build:
      context: ./ml_model
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    volumes:
      - minio_data:/data

volumes:
  minio_data:
