version: '3.8'

services:
  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=host=localhost user=postgres password=user dbname=sahla port=5432 sslmode=disable
      - JWT_SECRET=2T69rB5vNSo/tzaIiLUU7HqArofonOjUhc11mQOr0iIgwfn3Yzrkn1iENJI1sWI/b1ZE9Iyx6T7Sk6eMXWaVZg==
      - REFRESH_SECRET=cbagVQhtau+bJPgmrsljdguL6yXIpT8O8DnwcZvx48A=
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=ywWHlg62N1OVzrzJPOXc
      - MINIO_SECRET_KEY=CLoJyxgPN4WALTABCYOL7OZw7HD1FpQD8DqP9l3t
      - MINIO_USE_SSL=false
    depends_on:
      - postgres
      - minio
      - flask-api

  flask-api:
    build:
      context: ./ml-stuff
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=sahla
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=ywWHlg62N1OVzrzJPOXc
      - MINIO_SECRET_KEY=CLoJyxgPN4WALTABCYOL7OZw7HD1FpQD8DqP9l3t
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data:
